### ISSUE TITLE
Wrong default branch name

### ISSUE THREAD

**Issue by nekowinston** [JK-Flip-Flop96/powershell#1]
The default branch should be named `main`.

**Comment by JK-Flip-Flop96** [comment]
I had noticed this after I transferred the repo but I'd lost access to the repo settings necessary to make the change by then. Not sure who's got the ability to make that change?

**Comment by nekowinston** [comment]
When transferring repos, GitHub reduces your own access permissions from "Admin" to "Write", and we usually manually raise it to "Maintainer" again, looks like we forgot to do this in this case. I've just fixed that.

Also renamed the branch name. 🙂

**Comment by JK-Flip-Flop96** [comment]
Cheers 👍
